version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

jobs:
  #Build Job
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  #Test job
  test:
    <<: *defaults
    steps:
        - checkout
        - run: npm i
        - run: npm run test

  #Analyze job
  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm run audit



workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test